
trigger: none
#- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#create docker image 
#upload docker image  to the Docker hub.    
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'zekn-docker-hub'
        repository: 'zekn/azure_devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.yml
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
#build and publish artifact.  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifest'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

#download YAML, YML artifact files 
#from manifest package, which created previously
#to System.ArtifactsDirectory
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifest'
        itemPattern: |
          **/*.yaml
          **/*.yml
        targetPath: '$(System.ArtifactsDirectory)'

#deploy to kubernetes using previously downloaded yaml, yml files
#in this case will be used deployment.yaml file
#moreover will be used zekn/azure_devops:${tag} image
#tag is = build id
#The fully qualified URL of the image to be used for substitutions on the manifest files
# all references  are searched for in the image field of the input manifest files. 
#For each match found, the tag replaces the matched reference.
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'azure-k8s-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'zekn/azure_devops:$(tag)'