
trigger: none
#- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: copyFiles
    jobs:
      - job: copyFilesJob
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: |
              **/*.yml
              **/*.tf
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

      
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'